services:
  chimera:
    image: cefriel/chimera:kg4di
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./camel-routes:/app/camel-routes
      - ./input-gtfs:/app/input-gtfs
  dashboard:
    image: cefriel/chimera:kg4di-dashboard
    ports:
      - "8000:8000"
