services:
  chimera:
    image: cefriel/chimera:kg4di
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./camel-routes-solved/e3:/app
  dashboard:
    image: cefriel/chimera:kg4di-dashboard
    ports:
      - "8000:8000"
