PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tmjou: <https://w3id.org/mobility/transmodel/journeys#>



CONSTRUCT {
  ?place a wd:Q618123 ;
         rdfs:label ?placeLabel ;
         wdt:P625 ?coord ;
         schema:image ?image ;
	 geo:hasGeometry [ geo:asWKT ?coord ] .
}
WHERE {

    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-6.052050356808763 37.3490704814239)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.9790044340831 37.378397914551)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.9741825664079 37.383027172741)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.9667195447336 37.381616555328)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.9556213079565 37.380687299)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.9527245222207 37.375759490449)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.951588753856 37.371402628806)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.9504193107235 37.367625340448)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.9433303100607 37.353874279667)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    } UNION 
    {
      SERVICE wikibase:around {
        ?place wdt:P625 ?coord .
        bd:serviceParam wikibase:center "Point(-5.936324752177 37.346416130099)"^^geo:wktLiteral .
        bd:serviceParam wikibase:radius "0.5" .
      }
    }

  OPTIONAL { ?place wdt:P18 ?image . }

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en".
  }
}
LIMIT 25
